### ISSUE TITLE
onStartDiscoveryFailed with error #4

### ISSUE THREAD

**Issue by keephacking** [abhayastudios/nativescript-zeroconf#1]
demo-angular project is device throwing error
onStartDiscoveryFailed with error #4 on pressing the Start button in android device .

**Comment by abhayastudios** [comment]
I just commited some minor changes in v1.0.1. I don't think they will solve the problem you are experiencing, but it may be worth a shot.

**Comment by keephacking** [comment]
Hi @abhayastudios , Thanks for the fast response .  Iam trying to discover mdns service running in my nodemcu module . 
The type I used is   `private serviceType:string = '_http._tcp.';`

For testing I ran the demo-angular in my Redmi 4 (Android version 7.1.2) .
Not discovering this service on taping the `start` button in the demo app , but after taping multiple time its throwing this error `onStartDiscoveryFailed with error #4` . 
 
I also posted about this in SO https://stackoverflow.com/questions/51153306/not-able-to-browse-the-mdns-service-created-in-esp8266 .  **Thanks.**

**Comment by abhayastudios** [comment]
@keephacking actually I developed this plugin also for a device that my friend built also using the ESP 8266. I asked him to take a look at the SO post, maybe he can post some example code that works for him.

**Comment by keephacking** [comment]
@abhayastudios  , Thankyou very much .

**Comment by keephacking** [comment]
It was just a typo issue in my arduino code . Thanks .
