### ISSUE TITLE
Chance of upgrading to NS7?

### ISSUE THREAD

**Issue by matty0005** [abhayastudios/nativescript-zeroconf#12]
Hi, 
Since NS7 is becoming more adopted (including in my projects), i was wondering if we could get this plugin updated for NS7. 

I have had a go at this, and i can create a PR for the changes I've made. But unfortunately i haven't been able to get it to work just yet.

**Comment by matty0005** [comment]
I have made a PR, #13, hopefully to get this plugin updated in the near future.

**Comment by abhayastudios** [comment]
@matty0005 Hey man! Thanks a lot for the PR. I haven't had a chance yet to look at it, as I am swamped with other things. I'll promise to have a go at it sometime soon. Really appreciate the effort though!
Cheers

**Comment by matty0005** [comment]
@abhayastudios No worries - for the moment I'll just use the local copy I have.

I will note that the only thing I've noticed is that on iOS, it no longer returns the IP addresses - I'm working on a fix for that. Otherwise it seems to work fine across iOS and Android. 

I'll close this issue, and continue on in the PR
