### ISSUE TITLE
No services are found.

### ISSUE THREAD

**Issue by modeswitch** [abhayastudios/nativescript-zeroconf#4]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
Pixel 3 / Android 10

### Please, provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
  6.1.2
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
  6.1.2
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
  ```
  "tns-android": {
      "version": "6.1.2"
    },
    "tns-ios": {
      "version": "6.1.0"
    }
  ```
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
  ```
  "dependencies": {
    "nativescript-betterwebsockets": "^1.0.0",
    "nativescript-screen-orientation": "^2.0.0",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-videoplayer": "^4.2.1",
    "nativescript-zeroconf": "^1.0.2",
    "tns-core-modules": "~6.1.0"
  },
  "devDependencies": {
    "nativescript": "^6.1.2",
    "nativescript-dev-webpack": "~1.2.0"
  },
  ```
### Please, tell us how to recreate the issue in as much detail as possible. 
I've used the example code to try and find services but nothing is returned. I'm using `avahi-browse` on another computer to verify that my services are in fact discoverable.

I see in the log that service discovery has started:

```
10-28 19:21:15.555  1456  2267 D NsdService: Discover services
10-28 19:21:15.555  1456  2267 D NsdService: mdnssd [discover, 78, _http._tcp.]
10-28 19:21:15.558  1456  2267 D NsdService: Discover 6 78_http._tcp.
```

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

```
    this.zeroconf = new Zeroconf('_http._tcp.', 'local.'); // param 1 = service type, param 2 = domain
    this.zeroconf.on(
        Observable.propertyChangeEvent, 
        (data) => {
            switch(data.propertyName.toString()) {
                case 'serviceFound': {
                  console.log(`serviceFound: ${JSON.stringify(data.value)}`);
                  break;
                }
                case 'serviceLost': {
                  console.log(`serviceLost: ${JSON.stringify(data.value)}`);
                  break;
                }
            }
        }
    );
    this.zeroconf.startServiceDiscovery();
```

**Comment by abhayastudios** [comment]
Hi @modeswitch, honestly I haven't gotten around to trying the plugin on NS 6 so far. Might have something to do with that. What happens when you try to run the demo project?

**Comment by modeswitch** [comment]
I wasn't able to get the demo project to run at all. It didn't upgrade cleanly.

**Comment by abhayastudios** [comment]
I mean just "as is" (NS 3 or whatever it is). Sorry am traveling at the moment, so less available to check right now.

**Comment by modeswitch** [comment]
My system isn't set up for NS3 and getting the SDK manager to support multiple tools versions doesn't work as expected. :/

**Comment by abhayastudios** [comment]
@modeswitch It took me some time to get around to it, but upgraded the demo-angular project to NativeScript 6.3 and confirmed that it is still discovering zeroconf service both on iOS and Android. If it is still relevant, please have a try and re-open if necessary.
