### ISSUE TITLE
Resolve Hostname to IP?

### ISSUE THREAD

**Issue by matty0005** [abhayastudios/nativescript-zeroconf#7]
Is there anyway with this plugin, or via other methods that i can resolve a hostname.

This plugin returns the hostname, eg. `serviceFound: {"name":"FX DocuPrint M225 dw","type":"_printer._tcp.","host":"BRN3000000000.local.","port":515,"address":"{}"}'`

Is there a reason for only returning the hostname, and not an IP address?

Long story short, i need an IP address, and not a hostname - it just wont work for my case. Using multiple tools, i am able to see the IP address through the mDNS/zeroconf service discovery.

I have had a look around in the plugin to get an understanding on what is going on. What is interesting is that the `addresses` property comes back with an empty object.

Any help would be appreciated.

**Comment by abhayastudios** [comment]
@matty0005  honestly I don't remember exactly why but there was some kind of issue with addresses, not sure whether it was on iOS or Android. Had a quick look at iOS now and I see that the delegate actually does return an NSNetService object containing a pointer to the address. So I guess it would be possible to extract an IP address from it along the lines of this [example](https://stackoverflow.com/a/4976808/918269).

> I have had a look around in the plugin to get an understanding on what is going on. What is interesting is that the addresses property comes back with an empty object.

What platform did you try this on? Also which version of the platform?

**Comment by abhayastudios** [comment]
@matty0005 hey man have a look at release 1.0.4, the plugin should now also return an array of IP addresses both on iOS and Android.

**Comment by matty0005** [comment]
Thank you @abhayastudios. I have now been able to get the IP addresses.
